cart/urls.py
from django.urls import path
from .views import CartAddView, CartChangeView, CartRemoveView

app_name = "cart"

urlpatterns = [
    path("cart_add/", CartAddView.as_view(), name="cart_add"),
    path("cart_change/", CartChangeView.as_view(), name="cart_change"),
    path("cart_remove/", CartRemoveView.as_view(), name="cart_remove"),
]

djangoProject_all/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop.urls", namespace="shop")),
    path(
        "cart/",
        include("cart.urls", namespace="cart"),
    ),
    path(
        "user/",
        include("user.urls", namespace="user"),
    ),
    path(
        "order/",
        include("order.urls", namespace="order"),
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/urls.py
from django.urls import path
from order.views import CreateOrderView

app_name = "orders"

urlpatterns = [
    path("create_order/", CreateOrderView.as_view(), name="create_order"),
]

shop/urls.py
from django.urls import path
from .views import MainPageView, CategoryProductsListView, ProductDetailView

app_name = "shop"
urlpatterns = [
    path("", MainPageView.as_view(), name="main_page"),
    path("products/", CategoryProductsListView.as_view(), name="products_list"),
    path(
        "products/<slug:slug>/",
        CategoryProductsListView.as_view(),
        name="category_products",
    ),  # URL с slug
    path(
        "product/<slug:slug>/<str:article>",
        ProductDetailView.as_view(),
        name="product_details",
    ),
]

user/urls.py
from django.urls import path
from .views import (
    logout,
    UserLoginView,
    UserRegistrationView,
    UserProfileView,
    UserCartView,
)
from .view.email_views import (
    EmailConfirmationSentView,
    EmailConfirmedView,
    EmailConfirmationFailedView,
    UserConfirmEmailView,
)
from .view.user_password_views import (
    UserForgotPasswordView,
    UserPasswordResetConfirmView,
)

app_name = "user"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login_page"),
    path("registration/", UserRegistrationView.as_view(), name="registration_page"),
    path("profile/", UserProfileView.as_view(), name="profile_page"),
    path("user-cart/", UserCartView.as_view(), name="user_cart_page"),
    path("logout/", logout, name="logout_page"),
    path(
        "email-confirmation-sent/",
        EmailConfirmationSentView.as_view(),
        name="email_confirmation_sent",
    ),
    path(
        "confirm-email/<str:uidb64>/<str:token>/",
        UserConfirmEmailView.as_view(),
        name="confirm_email",
    ),
    path("email-confirmed/", EmailConfirmedView.as_view(), name="email_confirmed"),
    path(
        "confirm-email-failed/",
        EmailConfirmationFailedView.as_view(),
        name="email_confirmation_failed",
    ),
    path("password-reset/", UserForgotPasswordView.as_view(), name="password_reset"),
    path(
        "set-new-password/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
]

cart/models.py
from django.db import models

from shop.mixins import IdPrimaryKeyMixin
from shop.models.BaseModel import BaseModel
from shop.models.product_other import ProductVariant
from shop.models.product import Product
from user.models import User


class CartQuerySet(
    models.QuerySet
):  # Класс для управления моделью Cart с помощью Manager

    def total_price(self):  # Сумма всех продуктов в корзине
        return sum(
            cart.products_price() for cart in self
        )  # Возвращаем сумму цен всех продуктов

    def total_quantity(self):  # Количество продуктов в корзине
        if self:  # Если корзина не пустая
            return sum(
                cart.quantity for cart in self
            )  # Возвращаем сумму количества всех продуктов
        return 0  # Иначе возвращаем ноль


class Cart(IdPrimaryKeyMixin, models.Model):  # Класс для работы с корзиной

    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        verbose_name="Пользователь",
    )
    product_variant = models.ForeignKey(
        to=ProductVariant, on_delete=models.CASCADE, verbose_name="Вариант продукта"
    )  # Связываем корзину с вариантом продукта
    # Количество
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    session_key = models.CharField(
        max_length=32, blank=True, null=True, verbose_name="Ключ сессии"
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания"
    )

    class Meta:
        db_table = "cart"  # Имя таблицы
        verbose_name = "Корзину"  # Название модели
        verbose_name_plural = "Корзины"  # Название модели во множественном числе

    objects = (
        CartQuerySet.as_manager()
    )  # Класс для управления моделью Cart с помощью Manager

    def products_price(self):
        # Вычисляем стоимость продукта с учётом количества и скидки (sell_price)
        return round(self.product_variant.sell_price() * self.quantity, 2)

    def __str__(self):
        if self.user:  # Если пользователь авторизован
            # Возвращаем имя пользователя и название продукта и количество в корзине
            return f"Корзина {self.user.username} | Продукт {self.product_variant.product.title} | Количество {self.quantity}"
        # Если пользователь не авторизован, возвращаем название продукта и количество в корзине
        return f"Анонимная корзина | Продукт {self.product_variant.product.title} | Количество {self.quantity}"

cart/views.py
from django.views import View

from .models import Cart
from cart.mixins.CartMixin import CartMixin
from shop.models.product_other import ProductVariant
from django.http import HttpResponse, JsonResponse


class CartAddView(CartMixin, View):  # Класс для добавления продукта в корзину

    def post(self, request):  # Метод для добавления продукта в корзину
        article = request.POST.get(
            "article"
        )  # Запрашиваем идентификатор продукта из POST-запроса

        quantity = int(request.POST.get("quantity", 1))  # Количество из POST-запроса
        print(f"Количество: {quantity}")
        # Ищем вариант продукта по артикулу
        product_variant = ProductVariant.objects.get(article=article)

        # Проверяем, есть ли достаточно товара на складе
        if quantity > product_variant.stock:
            return JsonResponse({"error": "Недостаточно товара на складе."}, status=400)

        # Ищем корзину по варианту продукта
        cart = self.get_cart(request, product_variant=product_variant)

        # Вывод отладочной информации
        session_key = request.session.session_key
        if not session_key:
            request.session.create()
            session_key = request.session.session_key

        if cart:
            if cart.quantity + quantity > product_variant.stock:
                return JsonResponse(
                    {"error": "Недостаточно товара на складе"}, status=400
                )
            cart.quantity += 1
            cart.save()
        else:
            # Если корзины не существует, то создаем ее (если пользователь авторизован, то создаем корзину пользователя,
            # если не авторизован, то создаем корзину сессии)
            Cart.objects.create(
                user=request.user if request.user.is_authenticated else None,
                session_key=(
                    request.session.session_key
                    if not request.user.is_authenticated
                    else None
                ),
                product_variant=product_variant,
                quantity=1,
            )
        user_cart = self.get_cart_queryset(request)
        total_quantity = (
            user_cart.total_quantity()
            if callable(user_cart.total_quantity)
            else user_cart.total_quantity
        )
        total_price = (
            user_cart.total_price()
            if callable(user_cart.total_price)
            else user_cart.total_price
        )

        # Отправляем ответ с данными о добавлении в корзину
        response_data = {
            "cart_items_html": self.render_cart_add(request),
            "total_quantity": total_quantity,  # Количество продуктов в корзине
            "total_price": total_price,  # Сумма всех продуктов в корзине
        }

        return JsonResponse(response_data)


class CartChangeView(CartMixin, View):
    def post(self, request):
        cart_id = request.POST.get(
            "cart_id"
        )  # Запрашиваем идентификатор корзины из POST-запроса
        cart = self.get_cart(request, cart_id=cart_id)  # Ищем корзину по идентификатору
        cart.quantity = request.POST.get(
            "quantity"
        )  # Запрашиваем новое количество из POST-запроса
        cart.save()  # Сохраняем изменения в базе данных
        user_cart = self.get_cart_queryset(request)
        # Предполагая, что user_cart.total_quantity и user_cart.total_price возвращают вычисляемые значения
        total_quantity = (
            user_cart.total_quantity()
            if callable(user_cart.total_quantity)
            else user_cart.total_quantity
        )
        total_price = (
            user_cart.total_price()
            if callable(user_cart.total_price)
            else user_cart.total_price
        )

        response_data = {
            "include_cart_html": self.render_cart_change(request)[0],
            "user_cart_html": self.render_cart_change(request)[1],
            "total_quantity": total_quantity,
            "total_price": total_price,
        }
        return JsonResponse(response_data)


class CartRemoveView(CartMixin, View):
    def post(self, request):
        cart_id = request.POST.get(
            "cart_id"
        )  # Запрашиваем идентификатор корзины из POST-запроса
        cart = self.get_cart(request, cart_id=cart_id)  # Ищем корзину по идентификатору
        quantity = cart.quantity
        cart.delete()  # Удаляем объект корзины из базы данных
        user_cart = self.get_cart_queryset(request)
        # Предполагая, что user_cart.total_quantity и user_cart.total_price возвращают вычисляемые значения
        total_quantity = (
            user_cart.total_quantity()
            if callable(user_cart.total_quantity)
            else user_cart.total_quantity
        )
        total_price = (
            user_cart.total_price()
            if callable(user_cart.total_price)
            else user_cart.total_price
        )
        response_data = {
            "include_cart_html": self.render_cart_change(request)[0],
            "user_cart_html": self.render_cart_change(request)[1],
            "total_quantity": total_quantity,
            "total_price": total_price,
            "quantity_deleted": quantity,
        }
        return JsonResponse(response_data)

cart/templates/carts/includes/cart_page.html
{% load static %}
    <!--Body Content-->
    <div id="page-content" style="margin-top: 87px;">
    	<!--Page Title-->
    	<div class="page section-header text-center">
			<div class="page-title">
        		<div class="wrapper"><h1 class="page-width">Это ... моя корзина</h1></div>
      		</div>
		</div>
        <!--End Page Title-->
        
        <div class="container">
        	<div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 main-col">
                	{% if carts.total_price > 10000 %}
                    <div class="alert alert-success text-uppercase" role="alert">
						<i class="icon anm anm-truck-l icon-large"></i> &nbsp;<strong>Поздравляем!</strong> Вы получаете бесплатную доставку !
					</div>
                    {% endif %}
                	<form action="#" method="post" class="cart style2">
                		<table>
                            <thead class="cart__row cart__header">
                                <tr>
                                    <th colspan="2" class="text-center">Товар</th>
                                    <th class="text-center">Цена</th>
                                    <th class="text-center">Количество</th>
                                    <th class="text-right">Всего</th>
                                    <th class="action">&nbsp;</th>
                                </tr>
                            </thead>
                    		<tbody>
                            {% if not carts %} <tr> <td colspan="6"> <h3 style="display: block;text-align: center;background-color: ghostwhite;height: 31px;font-size: 21px;">Ваша корзина пуста 🙅</h3> </td> </tr> {% endif %}
                            {% for cart in carts %}
                            <tr class="cart__row border-bottom line1 cart-flex border-top">
                                    <td class="cart__image-wrapper cart-flex-item">
                                        <a href="#"><img class="cart__image" src="{{ cart.product_variant.product.main_image.image.url }}" alt="{{ cart.product_variant.product.title }}"></a>
                                    </td>
                                    <td class="cart__meta small--text-left cart-flex-item">
                                        <div class="list-view-item__title">
                                            <a href="#">{{ cart.product_variant.product.title }}</a>
                                        </div>
                                        
                                        <div class="cart__meta-text">
                                            Цвет: {{ cart.product_variant.color }}<br>Размер: {{ cart.product_variant.size }}<br>
                                        </div>
                                    </td>
                                    <td class="cart__price-wrapper cart-flex-item">
                                        <span class="money">{{ cart.product_variant.sell_price }} рублей</span>
                                    </td>
                                    <td class="cart__update-wrapper cart-flex-item text-right">
                                        <div class="cart__qty text-center">
                                            <div class="qtyField">
                                              <!-- Кнопка уменьшения количества -->
                                    <button type="button" style="height: 41px" class="qtyBtn minus" data-cart-change-url="{% url 'cart:cart_change' %}" data-cart-id="{{ cart.id }}">
                                        {% csrf_token %}
                                        <i class="fa anm anm-minus-r" aria-hidden="true"></i>
                                    </button>

                                    <!-- Поле для ввода количества -->
                                                <input type="number" style="width: 42px; padding:10px 6px; height:42px; border-radius:0; float: left;"
                                           id="form1" name="quantity" value="{{ cart.quantity }}" class="product-form__input"
                                            data-available-stock="{{ cart.product_variant.stock }}" min="1" max="{{ cart.product_variant.stock }}">

                                    <!-- Кнопка увеличения количества -->
                                    <button type="button" style="height: 41px" class="qtyBtn plus" data-cart-change-url="{% url 'cart:cart_change' %}" data-cart-id="{{ cart.id }}">
                                        {% csrf_token %}
                                        <i class="fa anm anm-plus-r" aria-hidden="true"></i>
                                    </button>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="text-right small--hide cart-price">
                                        <div><span class="money money-js" data-price="{{ cart.product_variant.sell_price }}">{{ cart.products_price }}</span> рублей</div>
                                    </td>
                                    <td class="text-center small--hide">
                                    <a href="{% url 'cart:cart_remove' %}" data-cart-id="{{ cart.id }}" class="btn btn--secondary cart__remove" title="Удалить товар">
                                        <i class="icon icon anm anm-times-l"></i>
                                    </a>
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                    		<tfoot>

                                <tr>
                                    <td colspan="3" class="text-left"><a href="{% url 'shop:products_list' %}" class="btn btn-secondary btn--small cart-continue">Продолжить покупки</a></td>
                                    <td colspan="3" class="text-right">
                                    	<button type="submit" href="{% url 'user:user_cart_page' %}" name="update" class="btn btn-secondary btn--small cart-continue ml-2">Обновить корзину</button>
                                    </td>
                                </tr>
                            </tfoot>
                    </table> 
                    </form>                   
               	</div>
                
                
                <div class="container mt-4">
                    <div class="row">
                    	<div class="col-12 col-sm-12 col-md-4 col-lg-4 mb-4">
                        	<h5>Промокод</h5>
                            <form action="#" method="post">
                            	<div class="form-group">
                                    <label for="address_zip">Введите свой промокод, если он у вас есть.</label>
                                    <input type="text" name="coupon">
                                </div>
                                <div class="actionRow">
                                    <div><input type="button" class="btn btn-secondary btn--small" value="Apply Coupon"></div>
                                </div>
                            </form>
                        </div>
                        <div class="col-12 col-sm-12 col-md-4 col-lg-4 mb-4">
                        	<h5>Рассчитайте стоимость доставки</h5>
							<form action="#" method="post">
                                <div class="form-group">
                                    <label for="address_country">Страна</label>
                                    <select id="address_country" name="address[country]" data-default="United States"><option value="Russia" data-provinces="[]">Российская Федерация</option>
                                        <option value="---" data-provinces="[]">---</option>
                                        <option value="Armenia" data-provinces="[]">Республика Армения</option>
                                        <option value="Azerbaijan" data-provinces="[]">Азербайджанская Республика</option>
                                        <option value="Belarus" data-provinces="[]">Республика Беларусь</option>
                                    </select>
                                </div>
                                   <div class="form-group">
                                    <label for="full_address">Адрес:</label>
                                    <input type="text" id="address_full" name="address[full]" required placeholder="г. Москва, Гагаринский переулок, д. 3, кв. 333">
                                </div>
                                <div class="form-group">
                                    <label for="address_zip">Почтовый индекс</label>
                                    <input type="text" id="address_zip" name="address[zip]" placeholder="119034">
                                </div>
    
                                <div class="actionRow">
                                    <div><input type="button" class="btn btn-secondary btn--small" value="Рассчитать доставку"></div>
                                </div>
                            </form>
                        </div>
                        
                        <div class="col-12 col-sm-12 col-md-4 col-lg-4 cart__footer">
                            <div class="solid-border">	
                              <div class="row border-bottom pb-2">
                                <span class="col-12 col-sm-6 cart__subtotal-title">Всего</span>
                                <span class="col-12 col-sm-6 text-right"><span class="money" id="total-price">{{ carts.total_price }}</span> рублей</span>
                              </div>
                              <div class="row border-bottom pb-2 pt-2">
                                <span class="col-12 col-sm-6 cart__subtotal-title">Доставка</span>
                                <span class="col-12 col-sm-6 text-right">Бесплатная доставка</span>
                              </div>
                              <div class="row border-bottom pb-2 pt-2">
                                <span class="col-12 col-sm-6 cart__subtotal-title"><strong>Общая сумма</strong></span>
                                <span class="col-12 col-sm-6 cart__subtotal-title cart__subtotal text-right"><span class="money" id="total-price-all">{{ carts.total_price }}</span> рублей</span>
                              </div>
                              <div class="cart__shipping">Стоимость доставки рассчитывается при оформлении заказа.</div>
                              <p class="cart_tearm">
                                <label>
                                  <input type="checkbox" name="tearm" class="checkbox" value="tearm" required="">
                                  Я согласен с правилами и условиями
								</label>
                              </p>
                              <input type="submit" name="checkout" id="cartCheckout" class="btn btn--small-wide checkout" 
                              onclick="window.location.href='{% url 'order:create_order' %}';"  value="Перейти к оформлению заказа">
                              <div class="paymnet-img"><img src="{% static "images/payment-img.jpg" %}" alt="Payment"></div>
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    <!--End Body Content-->

cart/templates/carts/includes/mini_cart.html
{% load static %}
{% load carts_tags %}
{#                    <div class="site-cart">#}
{#                    	<a href="#" class="site-header__cart" title="Корзина">#}
{#                        	<i class="icon anm anm-bag-l"></i>#}
{#                            <span id="CartCount" class="site-header__cart-count" data-cart-render="item_count">{{ cart.total_quantity }}</span>#}
{#                        </a>#}
                        <!--Миникорзина добавление-->
{#                        <div id="header-cart" class="block block-cart">#}
                        	<ul class="mini-products-list">
                            {% if not carts %}
                                <span style="display: block;text-align: center; font-size: 15px"> Ваша корзина пуста 🛒</span>
                            {% endif %} 
                                {% for cart in carts %}
                                <li class="item cart-item">
                                	<a class="product-image" href="{{ cart.product_variant.product.get_absolute_url }}">
                                    	<img src="{{ cart.product_variant.product.main_image.image.url }}" alt="{{ cart.product_variant.product.title }}" title="" />
                                    </a>
                                    <div class="product-details" >

                                <a href="{% url 'cart:cart_remove' %}" data-cart-id="{{ cart.id }}" class="remove cart__remove">
                                <i class="anm anm-times-l" aria-hidden="true" title="Удалить товар"></i>
                                </a>


                                <a class="pName" href="{{ cart.product_variant.product.get_absolute_url }}">
                                    {{ cart.product_variant.product.title }}
                                </a>

                                <div class="variant-cart">
                                    Цвет: {{ cart.product_variant.color }} / Размер: {{ cart.product_variant.size }}
                                </div>

                                <div class="wrapQtyBtn">
                                    <div class="qtyField">
                                        <span class="label">Количество: </span>

                                       <!-- Кнопка уменьшения количества -->
                                    <button type="button" style="height: 41px" class="qtyBtn minus" data-cart-change-url="{% url 'cart:cart_change' %}" data-cart-id="{{ cart.id }}">
                                        {% csrf_token %}
                                        <i class="fa anm anm-minus-r" aria-hidden="true"></i>
                                    </button>

                                    <!-- Поле для ввода количества -->
                                    <input type="number" style="width: 42px; padding:10px 6px; height:42px; border-radius:0; float: left;"
                                           id="form1" name="quantity" value="{{ cart.quantity }}" class="product-form__input"
                                     data-available-stock="{{ cart.product_variant.stock }}" min="1" max="{{ cart.product_variant.stock }}">

                                    <!-- Кнопка увеличения количества -->
                                    <button type="button" style="height: 41px" class="qtyBtn plus" data-cart-change-url="{% url 'cart:cart_change' %}" data-cart-id="{{ cart.id }}">
                                        {% csrf_token %}
                                        <i class="fa anm anm-plus-r" aria-hidden="true"></i>
                                    </button>
                                    </div>
                                </div>
                                        <div class="priceRow">
                                        	<div class="product-price">
                                            	<span class="money">{{ cart.product_variant.sell_price }} рублей</span>
                                            </div>
                                         </div>
									</div>
                                </li>
                                {% endfor %}
                            </ul>
                            <div class="total">
                            	<div class="total-in">
                                	<span class="label">Общая сумма:</span><span class="product-price"><span class="money" id="total-price-summary">{{ carts.total_price }}</span> рублей</span>
                                </div>
                                 <div class="buttonSet text-center">
                                    <a href="{% url 'user:user_cart_page' %}" class="btn btn-secondary btn--small">Корзина</a>
                                    <a href="checkout.html" class="btn btn-secondary btn--small">Оформить</a>
                                </div>
                            </div>
{#                        </div>#}
                        <!--End Minicart Popup-->
{#                    </div>#}