cart/urls.py
from django.urls import path
from .views import CartAddView, CartChangeView, CartRemoveView

app_name = "cart"

urlpatterns = [
    path("cart_add/", CartAddView.as_view(), name="cart_add"),
    path("cart_change/", CartChangeView.as_view(), name="cart_change"),
    path("cart_remove/", CartRemoveView.as_view(), name="cart_remove"),
]

djangoProject_all/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop.urls", namespace="shop")),
    path(
        "cart/",
        include("cart.urls", namespace="cart"),
    ),
    path(
        "user/",
        include("user.urls", namespace="user"),
    ),
    path(
        "order/",
        include("order.urls", namespace="order"),
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

order/models.py
from django.core.validators import RegexValidator
from django.db import models

from shop.mixins import IdPrimaryKeyMixin
from shop.models.product_other import ProductVariant

from user.models import User


class OrderItemQuerySet(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(IdPrimaryKeyMixin, models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.SET_DEFAULT,
        blank=True,
        null=True,
        verbose_name="Пользователь",
        default=None,
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания"
    )
    requires_delivery = models.BooleanField(
        default=False, verbose_name="Требуется доставка"
    )
    delivery_address = models.TextField(
        max_length=120, blank=True, null=True, verbose_name="Адрес доставки"
    )
    payment_on_get = models.BooleanField(
        default=False, verbose_name="Оплата при получении"
    )
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(
        max_length=50, default="В обработке", verbose_name="Статус заказа"
    )
    comment = models.TextField(
        blank=True, null=True, verbose_name="Комментарий к заказу"
    )
    email = models.EmailField(verbose_name="Электронная почта", blank=True, null=True)

    # Проверка номера телефона с помощью регулярного выражения
    phone_regex = RegexValidator(
        regex=r"^(\+7|7|8)?9\d{9}$",
        message="Номер телефона должен быть в формате: '+79XXXXXXXXX' или '89XXXXXXXXX'.",
    )
    # Поле для ввода номера телефона
    phone_number = models.CharField(
        validators=[phone_regex],
        max_length=15,
        blank=False,
        null=False,
        verbose_name="Номер телефона",
    )

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        ordering = ["-created_timestamp"]

    def __str__(self):
        if self.user:
            return f"Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name} | Статус {self.status}"
        return f"Заказ № {self.pk} | Анонимный покупатель | Статус {self.status}"

    def clean(self):
        if self.phone_number:  # Если поле не пустое
            normalized_number = self.normalize_phone_number(self.phone_number)
            self.phone_number = "+7" + normalized_number[-10:]

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    @staticmethod
    def normalize_phone_number(phone):
        phone = "".join(char for char in phone if char.isdigit())
        if len(phone) == 10 and phone.startswith("9"):
            return "7" + phone
        elif len(phone) == 11 and phone.startswith("8"):
            return "7" + phone[1:]
        return phone


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product_variant = models.ForeignKey(
        to=ProductVariant,
        on_delete=models.SET_DEFAULT,
        null=True,
        verbose_name="Продукт",
        default=None,
    )
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания"
    )

    class Meta:
        db_table = "order_product"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderItemQuerySet.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f"{self.order} | {self.product_variant.product.title} | {self.name} | {self.price} | {self.quantity}"

templates/includes/notifications.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/notifications/xbox_notifications.scss' %}">
 
<div class="notification-container">
    <div class="achievement">
        <div class="animation">
            <div class="circle">
                <div class="img trophy_animate trophy_img">
                    <img class="trophy_1" src="{% static 'img/notifications/trophy_full.svg' %}"/>
                    <img class="trophy_2" src="{% static 'img/notifications/trophy_no_handles.svg'%}">
                </div>
                <div class="img xbox_img">
                    <img src="{% static 'img/notifications/xbox.svg'%}"/>
                </div>
            </div>
            <div class="banner-outer">
                <div class="banner">
                    <div class="achieve_disp">
                        <span class="unlocked xbox_span" style="font-size: 10pt !important;">Достижение разблокировано:</span>
                        <div class="score_disp">
{#                            <div class="gamerscore">#}
{#                                <img width="20px" src="{% static 'img/notifications/G.svg'%}"/>#}
{#                                <span class="acheive_score">99</span>#}
{#                            </div>#}
                            <span class="achiev_name xbox_span" style="font-weight: bold">
                               {{ message }}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/Notifications/xbox_notifications.js' %}"></script>

templates/includes/preloader.html
{% load static %}


<style>
        /* Инлайн-стили для предзагрузки */
        #preloader {
            background-color: #161417;
            height: 100%;
            width: 100%;
            position: fixed;
            z-index: 99; /* Один из z-index был лишним */
            margin-top: 0;
            top: 0;
        }
        #loading-center {
            width: 100%;
            height: 100%;
            position: relative;
        }
        #loading-center-absolute {
            position: absolute;
            left: 50%;
            top: 50%;
            -webkit-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
        }
    </style>

 <!-- Предзагрузка -->
        <div id="preloader">
            <div id="loading-center">
                <div id="loading-center-absolute">
                    <img src="{% static "img/icon/preloader.svg" %}" alt="">
                </div>
            </div>
        </div>
        <!-- конец предзагрузки -->

 <!-- JS здесь -->
    <script src="{% static "js/vendor/jquery-3.4.1.min.js" %}"></script>
    <script src="{% static "js/main.js" %}"></script>

templates/includes/profile_table.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/profile/Table Responsive.css' %}">

<div class="profile-table-wrapper">
{#{% for order in orders %}#}
  <h1 class="h1-table-profile"><span class="blue">&lt;</span>{{ order.id }}<span class="blue">&gt;</span> <span class="yellow">Responsive</span></h1>
  <h2 class="h2-table-profile">Created with love by <a href="https://github.com/pablorgarcia" target="_blank">Pablo García</a></h2>

  <table class="profile-table-wrapper container-table-profile">
    <thead class="profile-table-wrapper">
      <tr>
        <th><h1 class="h1-table-profile" style="color: #dadada">Товар</h1></th>
        <th><h1 class="h1-table-profile" style="color: #dadada">Цвет</h1></th>
        <th><h1 class="h1-table-profile" style="color: #dadada">Размер</h1></th>
        <th><h1 class="h1-table-profile" style="color: #dadada">Количество</h1></th>
        <th><h1 class="h1-table-profile" style="color: #dadada">Цена</h1></th>
        <th><h1 class="h1-table-profile" style="color: #dadada">Общая стоимость</h1></th>
      </tr>
    </thead>
    <tbody>
{#    {% for item in order.orderitem_set.all %}#}
      <tr style="text-align: center">
        <td><a class="text-white" href="{{ item.product_variant.product.get_absolute_url }}">{{ item.name }}</a></td>
        <td>{{ item.product_variant.color }}</td>
        <td>{{ item.product_variant.size }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.price }} руб.</td>
        <td>{{ item.products_price }} руб.</td>
      </tr>
{#    {% endfor %}#}
    </tbody>
  </table>
{#{% endfor %}#}
</div>