cart/urls.py
from django.urls import path
from .views import CartAddView, CartChangeView, CartRemoveView

app_name = "cart"

urlpatterns = [
    path("cart_add/", CartAddView.as_view(), name="cart_add"),
    path("cart_change/", CartChangeView.as_view(), name="cart_change"),
    path("cart_remove/", CartRemoveView.as_view(), name="cart_remove"),
]

djangoProject_all/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("shop.urls", namespace="shop")),
    path(
        "cart/",
        include("cart.urls", namespace="cart"),
    ),
    path(
        "user/",
        include("user.urls", namespace="user"),
    ),
    path(
        "order/",
        include("order.urls", namespace="order"),
    ),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shop/urls.py
from django.urls import path
from .views import MainPageView, CategoryProductsListView, ProductDetailView

app_name = "shop"
urlpatterns = [
    path("", MainPageView.as_view(), name="main_page"),
    path("products/", CategoryProductsListView.as_view(), name="products_list"),
    path(
        "products/<slug:slug>/",
        CategoryProductsListView.as_view(),
        name="category_products",
    ),  # URL с slug
    path(
        "product/<slug:slug>/<str:article>",
        ProductDetailView.as_view(),
        name="product_details",
    ),
]

user/urls.py
from django.urls import path
from .views import (
    logout,
    UserLoginView,
    UserRegistrationView,
    UserProfileView,
    UserCartView,
)
from .view.email_views import (
    EmailConfirmationSentView,
    EmailConfirmedView,
    EmailConfirmationFailedView,
    UserConfirmEmailView,
)
from .view.user_password_views import (
    UserForgotPasswordView,
    UserPasswordResetConfirmView,
)

app_name = "user"

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="login_page"),
    path("registration/", UserRegistrationView.as_view(), name="registration_page"),
    path("profile/", UserProfileView.as_view(), name="profile_page"),
    path("user-cart/", UserCartView.as_view(), name="user_cart_page"),
    path("logout/", logout, name="logout_page"),
    path(
        "email-confirmation-sent/",
        EmailConfirmationSentView.as_view(),
        name="email_confirmation_sent",
    ),
    path(
        "confirm-email/<str:uidb64>/<str:token>/",
        UserConfirmEmailView.as_view(),
        name="confirm_email",
    ),
    path("email-confirmed/", EmailConfirmedView.as_view(), name="email_confirmed"),
    path(
        "confirm-email-failed/",
        EmailConfirmationFailedView.as_view(),
        name="email_confirmation_failed",
    ),
    path("password-reset/", UserForgotPasswordView.as_view(), name="password_reset"),
    path(
        "set-new-password/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
]

order/models.py
from django.core.validators import RegexValidator
from django.db import models

from shop.mixins import IdPrimaryKeyMixin
from shop.models.product_other import ProductVariant

from user.models import User


class OrderItemQuerySet(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(IdPrimaryKeyMixin, models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.SET_DEFAULT,
        blank=True,
        null=True,
        verbose_name="Пользователь",
        default=None,
    )
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания"
    )
    requires_delivery = models.BooleanField(
        default=False, verbose_name="Требуется доставка"
    )
    delivery_address = models.TextField(
        max_length=120, blank=True, null=True, verbose_name="Адрес доставки"
    )
    payment_on_get = models.BooleanField(
        default=False, verbose_name="Оплата при получении"
    )
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(
        max_length=50, default="В обработке", verbose_name="Статус заказа"
    )
    comment = models.TextField(
        blank=True, null=True, verbose_name="Комментарий к заказу"
    )
    email = models.EmailField(verbose_name="Электронная почта", blank=True, null=True)

    # Проверка номера телефона с помощью регулярного выражения
    phone_regex = RegexValidator(
        regex=r"^(\+7|7|8)?9\d{9}$",
        message="Номер телефона должен быть в формате: '+79XXXXXXXXX' или '89XXXXXXXXX'.",
    )
    # Поле для ввода номера телефона
    phone_number = models.CharField(
        validators=[phone_regex],
        max_length=15,
        blank=False,
        null=False,
        verbose_name="Номер телефона",
    )

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        ordering = ["-created_timestamp"]

    def __str__(self):
        if self.user:
            return f"Заказ № {self.pk} | Покупатель {self.user.first_name} {self.user.last_name} | Статус {self.status}"
        return f"Заказ № {self.pk} | Анонимный покупатель | Статус {self.status}"

    def clean(self):
        if self.phone_number:  # Если поле не пустое
            normalized_number = self.normalize_phone_number(self.phone_number)
            self.phone_number = "+7" + normalized_number[-10:]

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

    @staticmethod
    def normalize_phone_number(phone):
        phone = "".join(char for char in phone if char.isdigit())
        if len(phone) == 10 and phone.startswith("9"):
            return "7" + phone
        elif len(phone) == 11 and phone.startswith("8"):
            return "7" + phone[1:]
        return phone


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product_variant = models.ForeignKey(
        to=ProductVariant,
        on_delete=models.SET_DEFAULT,
        null=True,
        verbose_name="Продукт",
        default=None,
    )
    name = models.CharField(max_length=150, verbose_name="Название")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(
        auto_now_add=True, verbose_name="Дата создания"
    )

    class Meta:
        db_table = "order_product"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderItemQuerySet.as_manager()

    def products_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return f"{self.order} | {self.product_variant.product.title} | {self.name} | {self.price} | {self.quantity}"

user/models.py
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db import models

from shop.mixins.id_primary_key import IdPrimaryKeyMixin


class User(
    IdPrimaryKeyMixin, AbstractUser
):  # Класс для регистрации новых пользователей
    # Проверка номера телефона с помощью регулярного выражения
    phone_regex = RegexValidator(
        regex=r"^(\+7|7|8)?9\d{9}$",
        message="Номер телефона должен быть в формате: '+79XXXXXXXXX' или '89XXXXXXXXX'.",
    )
    # Поле для ввода номера телефона
    phone_number = models.CharField(
        validators=[phone_regex],
        max_length=17,
        blank=True,
        null=True,
        unique=True,
        verbose_name="Номер телефона",
    )

    class Meta:
        db_table = "user"
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def clean(self):  # Метод для проверки уникальности номера телефона
        if self.phone_number:  # Если поле не пустое
            # Нормализация номера телефона с помощью метода normalize_phone_number
            normalized_number = self.normalize_phone_number(self.phone_number)

            # Проверка уникальности номера телефона по его нормализованному значению в базе данных User
            if (
                User.objects.filter(phone_number__endswith=normalized_number[-10:])
                .exclude(pk=self.pk)
                .exists()
            ):
                # Если такой номер телефона уже зарегистрирован, выбрасывается исключение ValidationError
                raise ValidationError(
                    {"phone_number": "Этот номер телефона уже зарегистрирован."}
                )
            # Если номер телефона корректен, то сохраняется его в поле phone_number
            self.phone_number = "+7" + normalized_number[-10:]

    # Метод для сохранения нормализованного номера телефона в базе данных
    def save(self, *args, **kwargs):
        self.full_clean()  # Вызов метода full_clean, для того чтобы убедиться, что все проверки выполнены
        super().save(
            *args, **kwargs
        )  # Сохранение нормализованного номера телефона в базе данных

    @staticmethod  # Метод для нормализации номера телефона
    def normalize_phone_number(phone):
        phone = "".join(
            char for char in phone if char.isdigit()
        )  # Удаляет все символы, кроме цифр
        if len(phone) == 10 and phone.startswith(
            "9"
        ):  # Если длина номера 10 цифр и начинается с 9
            return "7" + phone  # Добавляет 7 в начало
        elif len(phone) == 11 and phone.startswith(
            "8"
        ):  # Если длина номера 11 цифр и начинается с 8
            return "7" + phone[1:]  # Удаляет первую цифру и добавляет 7 в начало
        return phone  # Возвращает нормализованный номер

order/forms.py
from django import forms
from .models import Order


class CreateOrderForm(forms.Form):
    first_name = forms.CharField(label="Имя", max_length=100)
    last_name = forms.CharField(label="Фамилия", max_length=100)
    email = forms.EmailField(label="Электронная почта")
    phone_number = forms.CharField(
        label="Телефон", validators=[Order.phone_regex], max_length=15
    )
    delivery_address = forms.CharField(
        label="Адрес доставки",
        required=False,
        widget=forms.TextInput(
            attrs={"id": "id_delivery_address"}
        ),  # Добавляем id для поля
    )
    payment_on_get = forms.ChoiceField(
        label="Способ оплаты",
        choices=[("0", "Оплата картой"), ("1", "Наличными/картой при получении")],
    )
    requires_delivery = forms.ChoiceField(
        label="Нужна доставка", choices=[("0", "Самовывоз"), ("1", "Нужна доставка")]
    )

    comment = forms.CharField(label="Комментарий к заказу", required=False)

user/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView

from cart.models import Cart
from order.models import Order, OrderItem
from user.forms import UserRegistrationForm, ProfileForm
from user.mixins.UserMixin import UserIsNotAuthenticated
from .services.tasks import send_activate_email_message_task


class UserLoginView(LoginView):
    template_name = "user/login.html"
    # form_class = UserLoginForm

    # success_url = reverse_lazy('main:home_page')

    def get_success_url(self):  # Перенаправление после успешного входа
        # Получаем параметр next (на какую страницу хотел зайти пользователь)
        redirect_page = self.request.GET.get("next", None)
        # Если параметр есть и страница "не выйти из аккаунта", то перенаправляем на запрашиваемую страницу
        if redirect_page and redirect_page != reverse("users:logout_page"):
            return redirect_page
        # Иначе перенаправляем на главную страницу
        return reverse_lazy("shop:main_page")

    def form_valid(
        self, form
    ):  # Проверка наличия сессионного ключа для неавторизованного пользователя
        # Получаем сессионный ключ
        session_key = self.request.session.session_key
        # Получаем пользователя
        user = form.get_user()
        # Если есть пользователь, то логиним его
        if user:
            auth.login(self.request, user)
            # Если есть сессионный ключ
            if session_key:
                # Присваиваем переменной forgot_carts значение корзин пользователя
                forgot_carts = Cart.objects.filter(user=user)
                # Если в корзине есть хотя бы одна корзина
                if forgot_carts.exists():
                    # Удаляем все корзины пользователя
                    forgot_carts.delete()
                # Обновляем значение сессионного ключа на авторизованного пользователя
                Cart.objects.filter(session_key=session_key).update(user=user)
                messages.success(self.request, f"{user.username}, Вы вошли в аккаунт")
                return HttpResponseRedirect(self.get_success_url())


class UserRegistrationView(
    UserIsNotAuthenticated, CreateView
):  # Форма регистрации пользователя
    # Имя шаблона для отображения формы регистрации
    template_name = "user/registration.html"
    # Форма регистрации пользователя с моделью User (поля для регистрации)
    form_class = UserRegistrationForm
    # Указываем URL, на которую будет перенаправлен пользователь после успешной регистрации
    success_url = reverse_lazy("shop:main_page")

    def form_valid(self, form):
        # Получаем сессионный ключ
        session_key = self.request.session.session_key
        # Получаем пользователя из формы данных (данные которые пришли с формы регистрации)
        user = form.save(commit=False)
        # Делаем пользователя неактивным до подтверждения email
        user.is_active = False
        user.save()

        # Отправляем email для активации
        send_activate_email_message_task.delay(user.id)

        # Если есть сессионный ключ
        if session_key:
            # Обновляем значение сессионного ключа на авторизованного пользователя
            Cart.objects.filter(session_key=session_key).update(user=user)

        # Выводим сообщение о том, что необходимо подтвердить email
        messages.success(
            self.request,
            f"{user.username}, пожалуйста, подтвердите свой электронный адрес. Письмо отправлено на {user.email}",
        )

        # Перенаправляем пользователя на страницу подтверждения отправки email
        return redirect("user:email_confirmation_sent")


# Класс для обновления профиля пользователя (данных профиля), LoginRequiredMixin - проверяет, залогинен ли пользователь
class UserProfileView(LoginRequiredMixin, UpdateView):  # CacheMixin
    # Имя шаблона для отображения профиля пользователя
    template_name = "user/profile.html"
    # Форма для обновления профиля пользователя
    form_class = ProfileForm
    # URL, на которую будет перенаправлен пользователь после успешного обновления профиля
    success_url = reverse_lazy("user:profile_page")

    # Функция для получения объекта пользователя
    def get_object(self, queryset=None):
        # Получаем объект пользователя
        return self.request.user

    # Функция для проверки формы для обновления профиля пользователя
    def form_valid(self, form):
        # Выводим сообщение об успешном обновлении профиля
        messages.success(self.request, f"Профиль успешно обновлен")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, f"Произошла ошибка при обновлении профиля")
        return super().form_invalid(form)

    # Функция для получения контекста для шаблона профиля пользователя
    def get_context_data(self, **kwargs):
        # Получаем контекст для шаблона профиля пользователя
        context = super().get_context_data(**kwargs)
        orders = (
            Order.objects.filter(user=self.request.user)
            .prefetch_related(
                Prefetch(
                    "orderitem_set",
                    queryset=OrderItem.objects.select_related("product_variant"),
                )
            )
            .order_by("-created_timestamp")
        )

        context["orders"] = orders

        return context


class UserCartView(TemplateView):  # Класс для отображения корзины пользователя
    template_name = (
        "user/user-cart.html"  # Имя шаблона для отображения корзины пользователя
    )


@login_required
def logout(request):
    auth.logout(request)
    messages.success(request, f"{request.user.username}, Вы успешно вышли из аккаунта")
    return redirect(reverse("shop:main_page"))

user/templates/user/profile.html
{% extends 'base.html' %}
{% load static %}


{% block title %}
    Личный профиль
{% endblock %}
{% block css_style %}
    <link rel="stylesheet" href="{% static 'css/profile/btn-order-hover.css' %}">
{% endblock %}

{% block main %}
    <section style="margin: 66px -13px; background: antiquewhite;">
    <!-- Контент -->
    <div class="container">
    <div class="row mt-1">
    <div class="col-lg-2">
        <!-- Пустой блок на усмотрение -->
    </div>
    <div class="col-lg-14">
    <!-- Контент на странице -->
    <div class="row">
    <div class="container mt-5">
    <div class="row">
    <!-- Профиль с данными пользователя -->
    <div class="col-md-5" style="position: relative; top: -40px; display: block;margin: 0 auto;">
        <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
            <h3 class="text-center mb-4 yellow_text">Профиль пользователя</h3>
            <form action="{% url 'user:profile_page' %}" method="post">
            {% csrf_token %}
                <div class="row">
                    <div class="col-md-12 mb-3 text-center">
                        <img src="{% static 'img/profile/free-png.ru-297-370x370.png' %}"
                             alt="Аватар пользователя" class="img-fluid rounded-circle"
                             style="max-width: 170px;">
                    </div>
                      <div class="col-md-12 mb-3">
                        <label for="id_username" class="form-label">Имя пользователя*</label>
                        <input type="text" class="form-control" id="id_username"
                        name="username" placeholder="Введите ваше имя пользователя" value="{{ form.username.value }}" disabled required>
                        {% if form.username.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                        {% endif %} 
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_first_name" class="form-label">Имя*</label>
                        <input type="text" class="form-control" id="id_first_name" 
                               name="first_name" placeholder="Введите ваше имя" value="{{ form.first_name.value }}" required>
                        {% if form.first_name.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                        {% endif %} 
                    </div>
                
                    <div class="col-md-12 mb-3">
                        <label for="id_last_name" class="form-label">Фамилия*</label>
                        <input type="text" class="form-control" id="id_last_name"
                               name="last_name" placeholder="Введите вашу фамилию" value="{{ form.last_name.value }}" required>
                        {% if form.last_name.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                        {% endif %} 
                    </div>
                    <div class="col-md-12 mb-3">
                        <label for="id_email" class="form-label">Email*</label>
                        <input type="email" class="form-control" id="id_email" 
                        name="email" placeholder="Введите ваш email" value="{{ form.email.value }}" required>
                        {% if form.email.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                        {% endif %} 
                    </div>   
                    <div class="col-md-12 mb-3">
                        <label for="id_phone_number">Номер телефона*</label>
                        <input class="form-control" id="id_phone_number" value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
                                name="phone_number" required type="text" placeholder="+79XXXXXXXXX"/>
                    {% if form.phone_number.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{ form.phone_number.errors }}</div>
                    {% endif %} 
                    </div>
                </div>
                <button type="submit" class="btn btn-dark">Сохранить</button>
            </form>
        </div>
    </div>
    <!-- Корзина -->
   
    <!-- Оформленные заказы -->

    <div class="col-md-12" style="position: relative; top: -50px">
    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">

    <h2 class="text-center mb-4 yellow_text">Мои заказы</h2>
    <!-- Разметка заказов -->

    <div class="container">
        <div class="accordion" id="accordionExample">
            {% for order in orders %}
             <div class="accordion-item">
                <h2 class="accordion-header" id="heading{{ order.id }}" style="text-align: center">
                    <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %} btn-order-hover" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}"
                            style="background: antiquewhite; color: black; border: solid;" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                        <strong>Заказ</strong> от {{ order.created_timestamp }} | Статус: <strong class="mx-2">{{order.status}}</strong>
                        <img src="{% static 'img/profile/icons8-шеврон-вниз-в-круге-50.png' %}" alt="" style="height: 31px">
                    </button>
                </h2>
                <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <table class="table table-dark table-hover">
                            <thead>
                                <tr style="text-align: center">
                                    <th>Товар</th>
                                    <th>Цвет</th>
                                    <th>Размер</th>
                                    <th>Количество</th>
                                    <th>Цена</th>
                                    <th>Общая стоимость</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in order.orderitem_set.all %}
                                <tr style="text-align: center">
                                    <td><a class="text-white" href="{{ item.product_variant.product.get_absolute_url }}">{{ item.name }}</a></td>
                                    <td>{{ item.product_variant.color }}</td>
                                    <td>{{ item.product_variant.size }}</td>
                                    <td>{{ item.quantity }}</td>
                                    <td>{{ item.price }} руб.</td>
                                    <td>{{ item.products_price }} руб.</td>
                                    
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div><!-- Закончилась разметка заказов -->
</div>

{% endblock %}
<!-- Закончилась разметка заказов -->
</div>

</div>
</div>
</div>
</div>
</div>
</div>


<script src="{% static 'js/jQueryv3.7.1.js' %}"></script>
<script src="{% static "js/bootstrap.bundle.min.js" %}"></script>

<script src="../deps/js/jquery-events.js"></script>
<script src="../deps/js/jquery-ajax.js"></script>


user/templates/user/registration.html
{% load static %}

<link rel="stylesheet" href="{% static "css/login/login.css" %}">
<link rel="stylesheet" href="{% static "css/registration/register.css" %}">
<link rel="stylesheet" href="{% static 'css/shake.css' %}">

<div class="breadcrumb"><a href="{% url "shop:main_page" %}">
    <h3 style="font-weight: 500"><span class="gentle-tilt-move-shake">Главная страница</span></h3></a>
</div>

<div class="open active">Создать аккаунт</div>
<div class="modal hidden">
  <div class="form">
    <form method="post" action="{% url 'user:registration_page' %}">
      {% csrf_token %}
      <label for="id_last_name">Фамилия</label>
      <input style="font-size: 11pt" id="id_last_name" value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
             name="last_name" type="text" placeholder="Введите вашу фамилию" autofocus/>
        {% if form.last_name.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
        {% endif %} 

      <label for="id_first_name">Имя</label>
      <input style="font-size: 11pt" id="id_first_name" value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
             name="first_name" type="text" placeholder="Введите ваше имя"/>
     {% if form.first_name.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
        {% endif %} 
        
      <label for="id_username">Имя пользователя</label>
      <input style="font-size: 11pt" id="id_username" value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
             name="username" required type="text" placeholder="Введите ваше имя пользователя"/>
     {% if form.username.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
        {% endif %} 

      <label for="id_phone_number">Номер телефона</label>
      <input style="font-size: 11pt" id="id_phone_number" value="{% if form.phone_number.value %}{{ form.phone_number.value }}{% endif %}"
             name="phone_number" required type="text" placeholder="+79XXXXXXXXX"/>
        {% if form.phone_number.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{ form.phone_number.errors }}</div>
        {% endif %} 
    
      <label for="id_email">Электронная почта</label>
      <input style="font-size: 11pt" id="id_email" value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
             name="email" type="email" placeholder="Введите адрес электронной почты" required/>
        {% if form.email.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
        {% endif %} 

      <label for="id_password1">Пароль</label>
      <input style="font-size: 11pt" id="id_password1" name="password1" type="password" required placeholder="Введите пароль"/> 
        {% if form.password1.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
        {% endif %} 
    
      <label for="id_password2">Подтвердите пароль</label>
      <input style="font-size: 11pt" id="id_password2" name="password2" type="password" required placeholder="Подтвердите пароль"/>
        {% if form.password2.errors %}
            <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
        {% endif %}

      <button type="submit">Зарегистрироваться</button>
    </form>
  </div>
  <div class="invite">
{#    <h3>Регистрация</h3>#}
    <div class="close" title="Закрыть"></div>
  </div>
</div>


<script src="{% static "js/jQueryv3.7.1.js" %}"></script>
<script src="{% static 'js/registration/register.js' %}"></script>

user/templates/user/user-cart.html
{% extends 'base.html' %}
{% load static %}
{% load products_tags %}

{% block title %}
    Корзина
{% endblock %}

{% block main %}
	{% include 'carts/includes/cart_page.html' %}
{% endblock %}

{% block script %}
	
{% endblock %}